"""Initial migration - create jobs table

Revision ID: 45d2fe3cfd59
Revises:
Create Date: 2025-11-26 05:45:05.604225

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '45d2fe3cfd59'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
